### ISSUE TITLE
The "Want" for native maps should link to the org's W3 web page

### ISSUE THREAD

**Issue by Malvoz** [Maps4HTML/chat#8]
It is of my opinion that the "[Web Want](https://github.com/WebWeWant/webwewant.fyi/blob/master/wants/61.md)" should link to the Maps4HTML [CG home page](https://www.w3.org/community/maps4html/) and/or the organizations' [Github page](https://github.com/Maps4HTML), in an objective manner.

@prushforth & @nchan0154 I can PR to include that, perhaps just a sentence at the end of the document? But I'm not sure how to word it, so if you agree can you help me with that?

This is to increase engagement, of course.

**Comment by prushforth** [comment]
Sure.  I submitted that and Nic also submitted something, but maybe we should PR it and ask for "We want native maps in the browser (and HTML)" and maybe link the We to http://maps4html.org ?

Or did you have some wording in mind, Robert?

**Comment by Malvoz** [comment]
Yes, your Want has been submitted properly and is live at https://webwewant.fyi/wants/61/.

Maybe the document should say something to the effect of:

"_The goal of the [W3C Maps4HTML Community Group](https://www.w3.org/community/maps4html/) is to establish a method for web developers to include interactive web maps within HTML documents._"

But perhaps you'd word that differently. :)

**Comment by Malvoz** [comment]
Oh, you meant that you'd include the phrase "We want native maps in the browser (and HTML)" as the link?

**Comment by prushforth** [comment]
Well, yes, but I like your impersonal phrasing, like we are an enormous community, which we are, but mostly in righteousness ;-).  Hopefully we'll get invited to pitch them!

Maybe, since it's attributed to Nic and me, we could say "Our goal, and the goal of the [W3C Maps4HTML Community Group](https://www.w3.org/community/maps4html/) is to establish a standard method for web developers to include interactive web maps within HTML documents." (I added "standard")

Maybe we should chat over [here](https://gitter.im/Maps4HTML), to avoid notification spam?
